[project]
name = "urban-sounds-classifier"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "datasets>=3.6.0",
    "librosa>=0.11.0",
    "soundfile>=0.13.1",
    "torch==2.2",
]
